



<section class="addUser">

    <form method="post" action="addUsers.php">

         <p>
            <label for="nom">Nom</label>
            <input type="text" name="nom" id="nom" value="<?= $tabPost['nom'] ?>" />
        </p>

        <p>
            <label for="prenom">Prenom</label>
            <input type="text" name="prenom" id="prenom" value="<?= $tabPost['prenom'] ?>" />
        </p>

        <p>
            <label for="mail">Mail</label>
            <input type="email" name="mail" id="mail" value="<?= $tabPost['mail'] ?>"  />
        </p>

         <p>
            <label for="password">Password</label>
            <input type="password" name="password" id="password"  />
        </p>

         <p>
            <label for="confirmPassword">Confirmation du Password</label>
            <input type="password" name="confirmPassword" id="confirmPassword"  />
        </p>

         <p>
            <label for="biographie">Biographie</label>
            <textarea name="biographie" id="biographie" value="">
                <?= $tabPost['bio'] ?>
            </textarea>
        </p>


        <p>
            <label for="avatar">avatar</label>
            <input type="text" name="avatar" id="avatar" value="<?= $tabPost['avatar'] ?>" />
        </p>

        <p>
            <label for="pseudo">Pseudo</label>
            <input type="text" name="pseudo" id="pseudo" value="<?= $tabPost['pseudo'] ?>" />
        </p>
         

        <p>
            <input type="submit" value="Insérer" />
        </p>
    </form>
</section>

