
<main class="login">

    <form method="POST" action="login.php">

        <p>
            <label for="pseudo">Pseuso</label>
            <input type="text" name="pseudo" id="pseudo" />
        </p>

        <p>
            <label for="Password">Mot de passe</label>
            <input type="password" name="Password" id="Password"  />
        </p>


        <input type="submit" value="Insérer" />


    </form>

</main>