<div class="panel panel-default">
	<div class="panel-heading">
		<?=$title?>
	</div>
	<div class="panel-body">
		<div class="row">
			<div class="col-lg-12">

					<?php if($erreur!=''): ?><div class="alert alert-danger" role="alert"><?=$erreur?></div><?php endif;?>
					<?php if(isset($values['idutilisateurs'])):?>
						<form action="editUser.php" method="POST">
						<input type="hidden" name="idutilisateurs" value="<?=$values['idutilisateurs']?>">
					<?php else:?>
						<form action="addUser.php" method="POST">
					<?php endif;?>
					<div class="form-group">
						<label for="nom">Nom :</label>
						<input class="form-control" type="text" value="<?=$values['nom']?>" name="nom" id="nom">
					</div>
					<div class="form-group">
						<label for="prenom">Prénom :</label>
						<input class="form-control" type="text" value="<?=$values['prenom']?>" name="prenom" id="prenom">
					</div>
					<div class="form-group">
						<label for="email">Email :</label>
						<input class="form-control" type="email" value="<?=$values['email']?>" name="email" id="email">
					</div>
					<div class="form-group">
						<label for="password">Mot de passe :</label>
						<input class="form-control" type="password" value="" name="password" id="password">
						<label for="passwordConf">Confirmez le mot de passe :</label>
						<input class="form-control" type="password" value="" name="passwordConf" id="passwordConf">
					</div>
					<div class="form-group">
						<label for="bio">Bio :</label>
						<textarea class="form-control" name="bio" id="bio"><?=$values['bio']?></textarea>
					</div>
						<div class="form-group">
						<label for="avatar">Avatar :</label>
						<textarea class="form-control" name="avatar" id="avatar"><?=$values['avatar']?></textarea>
					</div>
					<input type="submit" value="Enregistrer" class="btn btn-default">
					<input type="reset" value="Réinitialiser" class="btn btn-default">
				</form>
			</div>
			<!-- /.col-lg-12 (nested) -->
		</div>
		<!-- /.row (nested) -->
	</div>
	<!-- /.panel-body -->
</div>
